import {
  LayoutDashboard,
  Home,
  Boxes,
  FileStack,
  FolderOpen,
  Files,
  BookOpen,
  Newspaper,
  Image,
  Video,
  GalleryHorizontal,
  Users,
  UserRound,
  UserCog,
  Building2,
  Landmark,
  GraduationCap,
  Briefcase,
  Calendar,
  CalendarDays,
  ClipboardList,
  ScrollText,
  FileText,
  Receipt,
  ShoppingBag,
  ShoppingCart,
  Package,
  BadgeDollarSign,
  CreditCard,
  Wallet,
  BarChart3,
  PieChart,
  TrendingUp,
  TrendingDown,
  Activity,
  ChartColumn,
  Settings,
  Settings2,
  Wrench,
  Shield,
  ShieldCheck,
  Lock,
  KeyRound,
  Bell,
  Mail,
  MessageSquare,
  Phone,
  Globe,
  MapPinned,
  Map,
  Compass,
  Flag,
  Bookmark,
  BookmarkCheck,
  Star,
  Heart,
  Tag,
  Tags,
  Search,
  Filter,
  List,
  LayoutGrid,
  Rows3,
  SquareMenu,
  PanelLeft,
  PanelTop,
  Menu,
  ChevronRight,
  ChevronDown,
  Database,
  Server,
  Cloud,
  HardDrive,
  Archive,
  History,
  Clock3,
  Timer,
  Sparkles,
  CircleHelp,
  Info,
  Contact,
  Camera,
  ScanFace,
} from "lucide-react";
export const ICON_OPTIONS = [
  { key: "dashboard", icon: LayoutDashboard },
  { key: "home", icon: Home },
  { key: "pages", icon: FileStack },
  { key: "documents", icon: Files },
  { key: "folder", icon: FolderOpen },
  { key: "modules", icon: Boxes },
  { key: "news", icon: Newspaper },
  { key: "blog", icon: BookOpen },
  { key: "gallery", icon: Image },
  { key: "video", icon: Video },
  { key: "users", icon: Users },
  { key: "staff", icon: UserRound },
  { key: "roles", icon: UserCog },
  { key: "organization", icon: Building2 },
  { key: "office", icon: Landmark },
  { key: "education", icon: GraduationCap },
  { key: "services", icon: Briefcase },
  { key: "events", icon: CalendarDays },
  { key: "tasks", icon: ClipboardList },
  { key: "notice", icon: ScrollText },
  { key: "reports", icon: FileText },
  { key: "products", icon: Package },
  { key: "orders", icon: ShoppingCart },
  { key: "payments", icon: CreditCard },
  { key: "wallet", icon: Wallet },
  { key: "analytics", icon: BarChart3 },
  { key: "stats", icon: PieChart },
  { key: "growth", icon: TrendingUp },
  { key: "activity", icon: Activity },
  { key: "settings", icon: Settings },
  { key: "security", icon: ShieldCheck },
  { key: "database", icon: Database },
  { key: "server", icon: Server },
  { key: "cloud", icon: Cloud },
  { key: "notifications", icon: Bell },
  { key: "messages", icon: MessageSquare },
  { key: "mail", icon: Mail },
  { key: "contact", icon: Contact },
  { key: "globe", icon: Globe },
  { key: "location", icon: MapPinned },
  { key: "bookmark", icon: Bookmark },
  { key: "favorite", icon: Heart },
  { key: "star", icon: Star },
  { key: "tag", icon: Tag },
  { key: "grid", icon: LayoutGrid },
  { key: "list", icon: List },
  { key: "history", icon: History },
  { key: "clock", icon: Clock3 },
  { key: "camera", icon: Camera },
  { key: "help", icon: CircleHelp },
];
export const sampleImages = [
    {
      id: 1,
      url: 'https://images.unsplash.com/photo-1585036156171-384164a8c675?w=600&q=80',
      alt: 'Islamic architecture',
      overlayText: 'Mosque'
    },
    {
      id: 2,
      url: 'https://images.unsplash.com/photo-1529156069898-49953e39b3ac?w=600&q=80',
      alt: 'Youth gathering',
      overlayText: 'Youth Program'
    },
    {
      id: 3,
      url: 'https://images.unsplash.com/photo-1469571486292-0ba58a3f068b?w=600&q=80',
      alt: 'Community service',
      overlayText: 'Community Service'
    },
    {
      id: 4,
      url: 'https://images.unsplash.com/photo-1505330622279-bf7d7fc918f4?w=600&q=80',
      alt: 'Mosque interior',
      overlayText: 'Prayer Hall'
    }
  ];

